apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: pause.infra.doodle.com
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: NotIn
      values: ["controller-manager"]
