name: release-chart

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 #v3.5

      - name: Login to Github Container Registry using helm
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Package helm charts
        run: |
          helm package chart/k8s-pause -d chart

      - name: Publish helm charts to Github Container Registry
        run: |
          repository=$(echo "${{ github.repository_owner }}" | tr [:upper:] [:lower:])
          helm push ${{ github.workspace }}/chart/k8s-pause-*.tgz oci://ghcr.io/$repository/charts
